# Generated by Django 5.2.12 on 2026-04-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名稱')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='品牌 Logo')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌管理',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='車款名稱')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='售價（元）')),
                ('fuel_type', models.CharField(choices=[('gasoline', '汽油'), ('diesel', '柴油'), ('electric', '電動'), ('hybrid', '油電混合')], max_length=20, verbose_name='燃料類型')),
                ('transmission', models.CharField(choices=[('auto', '自動'), ('manual', '手動')], max_length=10, verbose_name='變速箱')),
                ('engine_cc', models.IntegerField(blank=True, null=True, verbose_name='排氣量（cc）')),
                ('seats', models.IntegerField(default=5, verbose_name='座位數')),
                ('description', models.TextField(blank=True, verbose_name='車款說明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='車款圖片')),
                ('is_available', models.BooleanField(default=True, verbose_name='上架中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '車款',
                'verbose_name_plural': '車款管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='留言')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('contacted', '已聯絡'), ('done', '已完成')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='詢問車款')),
            ],
            options={
                'verbose_name': '詢價紀錄',
                'verbose_name_plural': '詢價管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
